name: Update

on:
  # every Sunday at 00:00 UTC
  # https://crontab.guru/#0_0_*_*_0
  schedule:
    - cron: '0 0 * * 0'

  # https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_dispatch
  workflow_dispatch:

jobs:
  update-durations:
    runs-on: ubuntu-latest
    permissions:
      # necessary to open PR
      # https://github.com/peter-evans/create-pull-request#action-inputs
      contents: write
      pull-requests: write
    env:
      GIT_USER_NAME: Conda Bot
      GIT_USER_EMAIL: 18747875+conda-bot@users.noreply.github.com
    steps:
      - uses: actions/checkout@v3

      - name: configure git user
        run: |
          git config user.name '${{ env.GIT_USER_NAME }}'
          git config user.email '${{ env.GIT_USER_EMAIL }}'

      - name: download recent artifacts
        run: |
          gh run list \
            --branch main \
            --workflow tests \
            --limit 10 \
            --json databaseId \
            --jq '.[].databaseId' \
          | xargs \
            -n 1 \
          gh run download \
            --dir ${{ runner.temp }}/artifacts/ \
            --pattern '*-all' \
          || true
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: combine recent durations from artifacts
        run: |
          python ./tools/durations/combine.py ${{ runner.temp }}/artifacts/
          git commit --all --message "Update test durations"

      - name: sync files
        run: |
          pip install jinja2 pyyaml jsonschema pygithub
          python ./.github/sync.py ./.github/sync.yml
          git commit --all --message "Sync files"

      - name: create updated durations PR
        uses: peter-evans/create-pull-request@v5
        with:
          push-to-fork: conda-bot/conda
          token: ${{ secrets.DURATIONS_TOKEN }}
          branch: update-durations
          delete-branch: true
          title: 🤖 Update test durations
          body: |
            Aggregate recent test durations for each test and update the durations file.

            [durations.yml]: ${{ github.server_url }}/${{ github.repository }}/blob/main/.github/workflows/durations.yml

            This PR was created automatically by the [`durations.yml`][durations.yml] workflow.
